version: '3.3'

services:

  inbox:
    image: neicnordic/sda-inbox-sftp
    ports:
      - "2222:2222"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    environment:
      - CEGA_ENDPOINT
      - CEGA_ENDPOINT_CREDS
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
      - S3_ENDPOINT
      - BROKER_HOST
      - BROKER_USERNAME
      - INBOX_JKS_PATH
      - KEYSTORE_PASSWORD
    configs:
      - source: CA.cert
        target: /usr/local/share/ca-certificates/CA.cert
      - source: inbox.jks
        target: /etc/ega/inbox.jks
    volumes:
      - inbox:/ega/inbox

volumes:
  inbox:

configs:
  CA.cert:
    external: true
  inbox.jks:
    external: true
