version: '3.3'

services:

  certfixer:
    command:
      - /bin/sh
      - -c
      - |
        cp /origcerts/* /tls-certs
        chown -R nobody.nobody /tls-certs/*
        chmod -R og-rw /tls-certs/*-key.pem
        chown -R 100.101 /tls-certs/mq*
        chown -R 1000.1000 /tls-certs/cega*
        ls -la /tls-certs/ &&
        keytool -import \
                -trustcacerts \
                -file /tls-certs/ca.pem \
                -alias legaCA -storetype JKS \
                -keystore /tls/cacerts \
                -storepass "$${KEYSTORE_PASSWORD}" \
                -noprompt &&
        openssl pkcs12 -export \
                        -out /tls/keystore.p12 \
                        -inkey /tls-certs/inbox-key.pem \
                        -in /tls-certs/inbox.pem \
                        -passout pass:"$${KEYSTORE_PASSWORD}"

    container_name: certfixer
    image: neicnordic/openssl-alpine:latest
    volumes:
      - ./certs:/origcerts
      - certs:/tls-certs
      - java:/tls
    environment:
      - KEYSTORE_PASSWORD=testingthis
  inbox:
    image: neicnordic/sda-inbox-sftp
    ports:
      - "2222:2222"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    depends_on:
      - cega
      - mq
    environment:
      - CEGA_ENDPOINT=https://cega:8443/username/%s
      - CEGA_ENDPOINT_CREDS=legatest:OfEoDPVadIfd4CZUWkisrrVQbJ2yQPIH
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
      - S3_ENDPOINT
      - S3_BUCKET
      - BROKER_HOST=mq
      - BROKER_USERNAME=test
      - BROKER_PASSWORD=test
      - BROKER_VHOST=test
      - KEYSTORE_PATH=/etc/ssl/certs/java/keystore.p12
      - KEYSTORE_PASSWORD=testingthis
    volumes:
      - inbox:/ega/inbox
      - certs:/tls-certs
      - java:/etc/ssl/certs/java
    healthcheck:
      test: [ "CMD", "bash", "-c", "netstat -an | grep -q ':2222 '" ]
      interval: 5s
      timeout: 20s
      retries: 3

  cega:
    image: "egarchive/lega-base:release.v0.2.0"
    depends_on:
      - certfixer
    command:
      [
        "python",
        "/cega/users.py",
        "0.0.0.0",
        "8443",
        "/cega/users.json"
      ]
    environment:
      - LEGA_INSTANCES=legatest
      - CEGA_USERS_PASSWORD=OfEoDPVadIfd4CZUWkisrrVQbJ2yQPIH
      - CEGA_USERS_USER=legatest
    ports:
      - "8443:8443"
    volumes:
      - ./users.json:/cega/users.json
      - ./users.py:/cega/users.py
      - certs:/tls

  mq:
    container_name: mq
    image: ghcr.io/neicnordic/sda-mq:v1.4.0
    depends_on:
      - certfixer
    environment:
      - MQ_SERVER_CERT=/etc/rabbitmq/ssl/mq.pem
      - MQ_SERVER_KEY=/etc/rabbitmq/ssl/mq.key
      - MQ_CA=/etc/rabbitmq/ssl/ca.pem
      - MQ_USER=test
      - MQ_PASSWORD_HASH=C5ufXbYlww6ZBcEqDUB04YdUptO81s+ozI3Ll5GCHTnv8NAm
      - MQ_VHOST=test
      - MQ_VERIFY=verify_none
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    volumes:
      - ./certs/ca.pem:/etc/rabbitmq/ssl/ca.pem
      - ./certs/mq.pem:/etc/rabbitmq/ssl/mq.pem
      - ./certs/mq-key.pem:/etc/rabbitmq/ssl/mq.key
    healthcheck:
      test:
        [
          "CMD",
          "bash",
          "-c",
          "rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms"
        ]
      interval: 5s
      timeout: 120s
      retries: 3

volumes:
  inbox:
  certs:
  java:
